### ISSUE TITLE
Error running the example server.

### ISSUE THREAD

**Issue by jmalloc** [rinq/websocket#5]
Hey man, I've got an error trying to run the example server. 

I was initially trying to just run the client and connect it to `rinq/httpd`, but it gets a sub-protocol error; so I checked the headers and no sub-protocol is being sent. Then I thought I'd run the example server and at least made sure it was working there, which is when I encountered the error below.

```
06:09 rinq/websocket master: make serve-example-server 
cd example/server; make serve
yarn install
yarn install v0.16.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 6.85s.
PORT=8081 node --harmony --require babel-register src/app
module.js:471
    throw err;
    ^

Error: Cannot find module 'rinq-websocket/serialization/marshaller/command-response'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/james/dev/git/rinq/websocket/example/server/src/app.js:7:1)
    at Module._compile (module.js:570:32)
    at loader (/Users/james/dev/git/rinq/websocket/example/server/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/james/dev/git/rinq/websocket/example/server/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
make[1]: *** [serve] Error 1
make: *** [serve-example-server] Error 2
```

**Comment by ezzatron** [comment]
As discussed offline, the example server hasn't been updated for quite a while. More than likely it will get removed once we have a "real" WebSocket server.

**Comment by jmalloc** [comment]
No worries, I'll close this.
